# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-30 03:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import redactor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BidniiTuhai',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', redactor.fields.RedactorField()),
                ('video_file', models.FileField(blank=True, null=True, upload_to=b'')),
                ('video_url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Medee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('body', redactor.fields.RedactorField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('view', models.SmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='MedeeAngilal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('angilal', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Sudalgaa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('author_name', models.CharField(max_length=100)),
                ('pdf_file', models.FileField(upload_to=b'')),
            ],
        ),
        migrations.CreateModel(
            name='SudalgaaAngilal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Surgalt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(null=True)),
                ('video_file', models.FileField(null=True, upload_to=b'')),
                ('author_name', models.CharField(max_length=100)),
                ('author_email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='SurgaltAngilal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.AddField(
            model_name='surgalt',
            name='angilal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.SurgaltAngilal'),
        ),
        migrations.AddField(
            model_name='sudalgaa',
            name='angilal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.SudalgaaAngilal'),
        ),
        migrations.AddField(
            model_name='medee',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.MedeeAngilal'),
        ),
    ]
