# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-27 06:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20160420_0131'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sudalgaa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('author_name', models.CharField(max_length=100)),
                ('pdf_file', models.FileField(upload_to=b'')),
            ],
        ),
    ]
