# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-27 07:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_sudalgaa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Surgalt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(null=True)),
                ('video_file', models.FileField(null=True, upload_to=b'')),
                ('author_name', models.CharField(max_length=100)),
                ('author_email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='SurgaltAngilal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.AddField(
            model_name='surgalt',
            name='angilal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.SurgaltAngilal'),
        ),
    ]
