# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-27 07:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_auto_20160427_0727'),
    ]

    operations = [
        migrations.CreateModel(
            name='SudalgaaAngilal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.AddField(
            model_name='sudalgaa',
            name='angilal',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='web.SudalgaaAngilal'),
            preserve_default=False,
        ),
    ]
