# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-30 03:17
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='SystemUser',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('register', models.CharField(max_length=10, unique=True, verbose_name='\u0420\u0435\u0433\u0438\u0441\u0442\u0435\u0440:')),
                ('phone', models.IntegerField(verbose_name='\u0423\u0442\u0430\u0441:')),
                ('account', models.IntegerField(verbose_name=b'\xd0\x94\xd0\xb0\xd0\xbd\xd1\x81\xd0\xbd\xd0\xb8\xd0\xb9 \xd0\xb4\xd1\x83\xd0\xb3\xd0\xb0\xd0\xb0\xd1\x80:')),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Bank', verbose_name=b'\xd0\x91\xd0\xb0\xd0\xbd\xd0\xba:')),
            ],
            options={
                'abstract': False,
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
